### ISSUE TITLE
[BUG] Could not retrieve stock videos: generate_subtitles() missing 2 required positional arguments: 'sentences' and 'audio_clips'

### ISSUE THREAD

**Issue by damarnez** [FujiwaraChoki/MoneyPrinter#33] opened 2024-02-07 15:33 UTC
**Describe the bug**
Every time I try to generate a video it shows this error:
Could not retrieve stock videos: generate_subtitles() missing 2 required positional arguments: 'sentences' and 'audio_clips'

I'm using my local machine with ubuntu.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux

**Additional context**
I filled all the .env with all the providers but didn't work.

**Comment by raniaamina** [comment] 2024-02-07 16:04
also happen to me;

```bash
[-] Error: generate_subtitles() missing 2 required positional arguments: 'sentences' and 'audio_clips'
```

OS: Debian Sid
Python version: Python 3.11.7

**Comment by Seemslegitx** [comment] 2024-02-07 16:08
same error for me

**Comment by meetalif** [comment] 2024-02-07 16:20
Any solution guys?

**Comment by jensblond** [comment] 2024-02-07 16:30
same here.

I added:
`subtitles_path = generate_subtitles(tts_path, sentences, paths)`

in line 159 of main.py
Worked for me, but I still have the issue, that the audio is not added to the final video

**Comment by FujiwaraChoki** [comment] 2024-02-07 16:37
**Hi, this was an issue from someone who made a PR, I apologize for not noticing this earlier. Please pull from git again and the issue should be fine.**

**Comment by radry** [comment] 2024-02-07 16:58
> **Hi, this was an issue from someone who made a PR, I apologize for not noticing this earlier. Please pull from git again and the issue should be fine.**

Still doesn't work.

**Comment by FujiwaraChoki** [comment] 2024-02-07 17:06
> ![gambar](https://private-user-images.githubusercontent.com/22146607/303064828-470ff225-4afa-4d3b-924e-7fcd5b363cf5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMjU3NTEsIm5iZiI6MTcwNzMyNTQ1MSwicGF0aCI6Ii8yMjE0NjYwNy8zMDMwNjQ4MjgtNDcwZmYyMjUtNGFmYS00ZDNiLTkyNGUtN2ZjZDViMzYzY2Y1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDE3MDQxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkMmE3YmIwZTBkNjc2ZmEzYTUxNzFhY2M0MTdkYzUzMzQ0NGZhMjBiNDNhYWE5OGEwMTQwZjY2MTYwZTk3YmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QtiB2Jm9dl6sA5ZkK_ruzzo5okUhTXWYNWH0gD8Kab8)
> 
> testing recently and still happen. The process is stoped and the final video not created.

That means you didn't run `git pull`, as you can see the bug was fixed: https://github.com/FujiwaraChoki/MoneyPrinter/blob/f112a7165a91a660b98333b3ed19baa951e635ef/Backend/main.py#L162

**Comment by meetalif** [comment] 2024-02-07 17:07
Thanks. It's now fixed.

**Closed** 2024-02-07 17:06 UTC
Labels: bug, good first issue

**Comment by radry** [comment] 2024-02-07 17:16
> > ![gambar](https://private-user-images.githubusercontent.com/22146607/303064828-470ff225-4afa-4d3b-924e-7fcd5b363cf5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMjU3NTEsIm5iZiI6MTcwNzMyNTQ1MSwicGF0aCI6Ii8yMjE0NjYwNy8zMDMwNjQ4MjgtNDcwZmYyMjUtNGFmYS00ZDNiLTkyNGUtN2ZjZDViMzYzY2Y1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDE3MDQxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkMmE3YmIwZTBkNjc2ZmEzYTUxNzFhY2M0MTdkYzUzMzQ0NGZhMjBiNDNhYWE5OGEwMTQwZjY2MTYwZTk3YmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QtiB2Jm9dl6sA5ZkK_ruzzo5okUhTXWYNWH0gD8Kab8)
> > testing recently and still happen. The process is stoped and the final video not created.
> 
> That means you didn't run `git pull`, as you can see the bug was fixed:
> 
> https://github.com/FujiwaraChoki/MoneyPrinter/blob/f112a7165a91a660b98333b3ed19baa951e635ef/Backend/main.py#L162

That line isn't the issue.
```
MoviePy - Writing audio in ../temp/b6354402-ac06-4c93-9a3d-224e2d472b84.mp3
MoviePy - Done.
[-] Error: generate_subtitles() missing 2 required positional arguments: 'sentences' and 'audio_clips'
127.0.0.1 - - [07/Feb/2024 18:12:03] "POST /api/generate HTTP/1.1" 200 -
```
Maybe this is the cause? 
`Line 159: subtitles_path = generate_subtitles(tts_path) `

Yes, I did git pull several times, now. Still latest version.

**Comment by FujiwaraChoki** [comment] 2024-02-07 17:22
I can't find the line you're talking about - I suspect there's some problems with git, do you perhaps mean this line of code?

https://github.com/FujiwaraChoki/MoneyPrinter/blob/f112a7165a91a660b98333b3ed19baa951e635ef/Backend/main.py#L155

**Comment by FujiwaraChoki** [comment] 2024-02-07 17:22
I would suggest removing MoneyPrinter and re-cloning it.
